import 'package:flutter/material.dart';

import '../interfaces/itheme.dart';
import '../tokens/tokens.dart';

class DefaultTheme extends ITheme {
  DefaultTheme()
      : super(
          tokenColors: TokenColors(
            brightness: Brightness.light,
            errorContainer: const Color(0xFFB00020),
            inversePrimary: const Color(0xFFFFFFFF),
            inverseSurface: Colors.black,
            primary: const Color(0xFF254155),
            primaryContainer: const Color(0xFFE5E5E5),
            secondary: const Color(0xFF03DAC6),
            secondaryContainer: const Color(0xFFE5E5E5),
            background: const Color(0xFFE5E5E5),
            error: const Color(0xFFB00020),
            onBackground: const Color(0xFF000000),
            onPrimary: const Color(0xFFFFFFFF),
            onSecondary: const Color(0xFF000000),
            onError: const Color(0xFFFFFFFF),
            onErrorContainer: const Color(0xFFB00020),
            onInverseSurface: const Color(0xFF000000),
            onPrimaryContainer: const Color(0xFF000000),
            onSecondaryContainer: const Color(0xFF000000),
            onSurface: const Color(0xFF000000),
            surface: const Color(0xFF000000),
            onSurfaceVariant: const Color(0xFF000000),
            onTertiary: const Color(0xFF000000),
            onTertiaryContainer: const Color(0xFF000000),
            outline: const Color(0xFF000000),
            outlineVariant: const Color(0xFF000000),
            scrim: const Color(0xFF000000),
            shadow: const Color(0xFF000000),
            surfaceTint: const Color(0xFF000000),
            surfaceVariant: const Color(0xFF000000),
            tertiary: const Color(0xFF000000),
            tertiaryContainer: const Color(0xFF000000),
          ),
          tokenPadding: TokenPadding(
            verticalSmallSpacing: 4,
            verticalMediumSpacing: 8,
            verticalHugeSpacing: 16,
            verticalLargeSpacing: 22,
            verticalExtraLargeSpacing: 32,
            horizontalSmallSpacing: 4,
            horizontalMediumSpacing: 8,
            horizontalLargeSpacing: 16,
            horizontalHugeSpacing: 22,
            horizontalExtraLargeSpacing: 32,
            cardPadding: const EdgeInsets.all(16),
            mainPadding: const EdgeInsets.all(16),
            mediumPadding: const EdgeInsets.all(16),
            smallPadding: const EdgeInsets.all(8),
            largePadding: const EdgeInsets.all(22),
          ),
          tokenTextTheme: TokenTextTheme(
            bodyLarge: const TextStyle(color: Colors.red, fontSize: 16, fontWeight: FontWeight.w700),
            bodyMedium: const TextStyle(),
            bodySmall: const TextStyle(),
            displayLarge: const TextStyle(),
            displayMedium: const TextStyle(),
            displaySmall: const TextStyle(),
            headlineLarge: const TextStyle(),
            headlineMedium: const TextStyle(),
            headlineSmall: const TextStyle(),
            labelLarge: const TextStyle(),
            labelMedium: const TextStyle(),
            labelSmall: const TextStyle(),
            overline: const TextStyle(),
            titleLarge: const TextStyle(),
            titleMedium: const TextStyle(),
            titleSmall: const TextStyle(),
          ),
          tokenInputDecorationTheme: const TokenInputDecorationTheme(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(8)),
              borderSide: BorderSide(color: Color(0xFFE5E5E5)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(8)),
              borderSide: BorderSide(color: Color(0xFF254155)),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(8)),
              borderSide: BorderSide(color: Color(0xFFB00020)),
            ),
            focusedErrorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(8)),
              borderSide: BorderSide(color: Color(0xFFB00020)),
            ),
            disabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(8)),
              borderSide: BorderSide(color: Color(0xFFE5E5E5)),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(8)),
              borderSide: BorderSide(color: Color(0xFFE5E5E5)),
            ),
            labelStyle: TextStyle(color: Color(0xFF254155)),
            errorStyle: TextStyle(color: Color(0xFFB00020)),
          ),
          tokenIconTheme: const TokenIconTheme(
            size: 24,
            color: Color(0xFF254155),
          ),
          tokenDrawerTheme: TokenDrawerTheme(
            backgroundColor: const Color(0xFFE5E5E5),
            elevation: 16,
            width: 304,
          ),
          tokenDividerTheme: const TokenDividerTheme(
            color: Color(0xFFE5E5E5),
            thickness: 1,
          ),
          tokenCardTheme: TokenCardTheme(
            color: const Color(0xFFE5E5E5),
            elevation: 16,
            borderRadius: BorderRadius.circular(8),
            margin: EdgeInsets.zero,
            surfaceTintColor: Colors.black,
            shadowColor: Colors.black,
          ),
          tokenAppBarTheme: TokenAppBarTheme(backgroundColor: Colors.white),
          tokenBottomSheetTheme: TokenBottomSheetTheme(
            backgroundColor: const Color(0xFFE5E5E5),
            elevation: 16,
            modalBackgroundColor: const Color(0xFFE5E5E5),
            modalElevation: 16,
            borderRadius: BorderRadius.zero,
          ),
          tokenBottomNavigationBarTheme: const TokenBottomNavigationBarTheme(),
          tokenButtonsTheme: TokenButtonsTheme(
            tokenElevatedButtonTheme: TokenElevatedButtonTheme(
              overlayColor: Colors.red,
              backgroundColor: Colors.red,
              borderRadius: BorderRadius.circular(8),
              disabledColor: Colors.grey,
              elevation: 16,
              disabledTextColor: Colors.grey,
              padding: const EdgeInsets.all(16),
              textStyle: const TextStyle(color: Colors.white),
              foregroundColor: Colors.white,
            ),
            tokenOutlinedButtonTheme: TokenOutlinedButtonTheme(
              borderWidth: 1,
              disabledColor: Colors.grey,
              borderRadius: BorderRadius.circular(8),
              disabledTextColor: Colors.grey,
              padding: const EdgeInsets.all(16),
              textStyle: const TextStyle(color: Colors.white),
              foregroundColor: Colors.white,
            ),
            tokenTextButtonTheme: TokenTextButtonTheme(
              disabledTextColor: Colors.grey,
              fontSize: 16,
              fontWeight: FontWeight.w700,
              textColor: Colors.white,
            ),
          ),
          tokenDialogTheme: TokenDialogTheme(
            backgroundColor: const Color(0xFFE5E5E5),
            elevation: 16,
            borderRadius: BorderRadius.circular(8),
          ),
        );
}
